import { Command } from 'commander';
import fs from 'fs-extra';
import path from 'path';
import readline from 'readline';
import { findProjectRoot } from '../utils/fs';
import { readProgress, writeProgress } from '../engine/progress';
import { renderRoadmapFile, STAGE_STUB_TEMPLATE } from '../utils/roadmap';

// ── Helpers ───────────────────────────────────────────────────────────────────

function promptApprove(message: string): Promise<boolean> {
  return new Promise(resolve => {
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    rl.question(`${message}\nType APPROVE to continue: `, answer => {
      rl.close();
      resolve(answer.trim().toUpperCase() === 'APPROVE');
    });
  });
}

function extractStageTitleFromPlan(filePath: string): string {
  if (!fs.existsSync(filePath)) return '(TBD)';
  try {
    const content = fs.readFileSync(filePath, 'utf8');
    // Match: "Source Roadmap Stage: Stage X.Y (Title)" or bold variant
    const match = content.match(/\*{0,2}Source Roadmap Stage\*{0,2}\s*:\s*.*Stage\s+[\d.]+[^(]*\(([^)]+)\)/i);
    if (match) return match[1].trim();
    // Also handle "N/A"
    const naMatch = content.match(/\*{0,2}Source Roadmap Stage\*{0,2}\s*:\s*N\/A/i);
    if (naMatch) return '(TBD)';
    return '(TBD)';
  } catch {
    return '(TBD)';
  }
}

function generateRoadmapFromPlans(
  stages: Array<{ version: string; title: string }>
): string {
  const stageDetailBlocks = stages
    .map(s => STAGE_STUB_TEMPLATE(s.version).replace('(title TBD)', s.title))
    .join('');

  return `# ROADMAP

> FMN-owned implementation staging document. ROADMAP breaks a locked Director Intent into build stages before each stage is converted into FMN-PLAN. ROADMAP is mandatory — \`sigma plan new\` requires a ROADMAP for the current INTENT version.
> ROADMAP version = INTENT major version. ROADMAP stays DRAFT throughout the project and auto-locks on \`sigma close lock\`.

---

## 1. Roadmap Purpose

Why this roadmap exists:

[Migrated from legacy ROADMAP — fill in or copy from ROADMAP-legacy file]

What this roadmap helps prevent:

- oversized FMN-PLAN
- unclear build order
- missing dependency sequencing
- premature implementation
- unmanaged scope expansion

---

## 2. Source Intent Alignment

Summarize how this roadmap serves the locked DIR-INTENT.

- Intent point served:
- Success criteria supported:
- Scope boundary respected:
- Constraint or risk addressed:
- Primary trade-off preserved:

---

<!-- SIGMA:RENDER:START:stage-overview -->
## 3. Stage Overview

| Stage | Title | Focus | Status |
| :--- | :--- | :--- | :--- |

<!-- SIGMA:RENDER:END:stage-overview -->

---

<!-- SIGMA:ROADMAP:SECTION:CORE_PROCESS_FLOW -->
## 4. Core Process Flow

> Manual section. FMN writes the high-level product/system flow here.
> This section is not regenerated by \`sigma roadmap render\`.

[Migrate or rewrite the main product/system flow from the legacy ROADMAP]

---

## 5. Stage Details

> H2 stage sections below were migrated from the legacy ROADMAP. Do not write \`## Stage X.Y\` headings manually.
> FMN fills the H3 body content (Focus, Main Output, Main Tasks, etc.) — migrate from ROADMAP-legacy file.

---

<!-- SIGMA:RENDER:START:plan-breakdown -->
## 6. PLAN Breakdown

| PLAN | Covers Stage | Title | Focus | Status | Reason |
| :--- | :--- | :--- | :--- | :--- | :--- |

<!-- SIGMA:RENDER:END:plan-breakdown -->

---

## 7. FMN Roadmap Notes

FMN notes:

[Migrate from legacy ROADMAP]

Recommended next PLAN:

[...]

---

## Roadmap Policy

ROADMAP is mandatory. \`sigma plan new\` is blocked without a ROADMAP for the current INTENT version.

ROADMAP is FMN-owned.

ROADMAP lives in BUILD context (\`Sigma/build/\`).

ROADMAP is a living document — freely editable until project close.

ROADMAP auto-locks when \`sigma close lock\` is executed. FMN does not manually lock ROADMAP.

H2 stage headings (\`## Stage X.Y — Title\`) are created only by \`sigma plan new\`. Never write them manually.

Derived sections (Stage Overview, PLAN Breakdown) are regenerated by \`sigma roadmap render\`. Never edit them manually.

Core Process Flow is manual. \`sigma roadmap render\` must never overwrite it.

FMN fills only the H3 body content within each stage section.
${stageDetailBlocks}`;
}

// ── sync progress ─────────────────────────────────────────────────────────────

function runSyncProgress(projectRoot: string): void {
  const progressPath = path.join(projectRoot, 'Sigma', 'progress.json');
  if (!fs.existsSync(progressPath)) {
    throw new Error('No progress.json found. Run: sigma project start');
  }

  let raw: Record<string, unknown>;
  try {
    raw = fs.readJsonSync(progressPath) as Record<string, unknown>;
  } catch {
    throw new Error('progress.json is not valid JSON — cannot migrate');
  }

  const changes: string[] = [];

  // 1. Coerce exec versions: BUILDING / TESTING / COMPLETED → DRAFT
  const exec = raw.exec as Record<string, unknown> | undefined;
  if (exec && Array.isArray(exec.versions)) {
    for (const v of exec.versions as Array<Record<string, unknown>>) {
      if (typeof v.state === 'string' && ['BUILDING', 'TESTING', 'COMPLETED'].includes(v.state)) {
        changes.push(`  exec.${v.version}: ${v.state} → DRAFT`);
        v.state = 'DRAFT';
        if (exec.active_version === v.version) {
          exec.active_state = 'DRAFT';
        }
      }
    }
  }

  // 2. Strip cso array if present
  if ('cso' in raw) {
    const csoCount = Array.isArray(raw.cso) ? (raw.cso as unknown[]).length : '?';
    changes.push(`  Removed cso array (${csoCount} entries) — CSO files in Sigma/logs/ are untouched`);
    delete raw.cso;
  }

  // 3. Ensure plan.pending exists (backward compat)
  const plan = raw.plan as Record<string, unknown> | undefined;
  if (plan && !Array.isArray(plan.pending)) {
    changes.push('  Added plan.pending: [] (backward compatibility)');
    plan.pending = [];
  }

  if (changes.length === 0) {
    console.log('progress.json is already up to date. No changes needed.');
    return;
  }

  console.log('\nSync Progress — changes to apply:\n');
  for (const c of changes) console.log(c);
  console.log('');

  const tmpPath = progressPath + '.tmp';
  fs.writeJsonSync(tmpPath, raw, { spaces: 2 });
  fs.moveSync(tmpPath, progressPath, { overwrite: true });
  console.log(`Applied ${changes.length} change(s) to progress.json.`);
}

// ── sync roadmap ──────────────────────────────────────────────────────────────

async function runSyncRoadmap(projectRoot: string, yes: boolean): Promise<void> {
  const data = readProgress(projectRoot);

  // Find ACTIVE roadmap
  const activeRoadmap = data.roadmap.versions.find(v => v.state === 'ACTIVE');
  if (!activeRoadmap) {
    throw new Error(
      'No ACTIVE ROADMAP found.\n' +
      'Run: sigma roadmap new   to create one\n' +
      'Or:  sigma roadmap activate --v <ver>   to activate a DRAFT'
    );
  }

  // Get locked plan versions in order
  const lockedPlans = data.plan.versions
    .filter(v => v.state !== 'SUPERSEDED')
    .sort((a, b) => a.version.localeCompare(b.version));

  if (lockedPlans.length === 0) {
    throw new Error('No non-superseded plan versions found in progress.json. Nothing to migrate.');
  }

  // Build stage list from plan files
  console.log('\nExtracting stage titles from FMN-PLAN files...\n');
  const stages: Array<{ version: string; title: string }> = [];
  for (const plan of lockedPlans) {
    const stageVersion = plan.version.replace(/^v/, '');
    const planAbsPath = plan.file ? path.join(projectRoot, plan.file) : null;
    const title = planAbsPath ? extractStageTitleFromPlan(planAbsPath) : '(TBD)';
    const warning = title === '(TBD)' ? ' ⚠ (title could not be extracted — fill manually)' : '';
    console.log(`  ${plan.version} → Stage ${stageVersion}: "${title}"${warning}`);
    stages.push({ version: stageVersion, title });
  }

  const roadmapRelPath = activeRoadmap.file ?? path.join('Sigma', 'build', `ROADMAP-${activeRoadmap.version}.md`);
  const roadmapAbsPath = path.join(projectRoot, roadmapRelPath);
  const legacyAbsPath = roadmapAbsPath.replace(/\.md$/, `-legacy.md`);

  console.log(`\nThis will:`);
  console.log(`  1. Rename: ${roadmapRelPath} → ${path.relative(projectRoot, legacyAbsPath)}`);
  console.log(`  2. Generate: new ${roadmapRelPath} with ${stages.length} stage sections + delimiter comments`);
  console.log(`  3. Run: sigma roadmap render  (populate Stage Overview and PLAN Breakdown)`);
  console.log(`\nThe legacy file is NOT deleted — migrate H3 body content from it manually.\n`);

  if (!yes) {
    const approved = await promptApprove('');
    if (!approved) {
      console.log('Sync roadmap cancelled.');
      return;
    }
  }

  // Rename existing ROADMAP to legacy
  if (fs.existsSync(roadmapAbsPath)) {
    fs.moveSync(roadmapAbsPath, legacyAbsPath, { overwrite: false });
    console.log(`Renamed: ${path.relative(projectRoot, roadmapAbsPath)} → ${path.relative(projectRoot, legacyAbsPath)}`);
  }

  // Generate new ROADMAP file
  const newContent = generateRoadmapFromPlans(stages);
  fs.ensureDirSync(path.dirname(roadmapAbsPath));
  fs.writeFileSync(roadmapAbsPath, newContent, 'utf8');
  console.log(`Generated: ${roadmapRelPath}`);

  // Render derived sections
  renderRoadmapFile(roadmapAbsPath, data);
  console.log('Rendered: Stage Overview, PLAN Breakdown');

  console.log('\nSync complete.');
  console.log(`Open ${path.relative(projectRoot, legacyAbsPath)} and migrate H3 body content section by section.`);
  console.log('');
}

// ── Command builder ───────────────────────────────────────────────────────────

export function syncCommand(): Command {
  const cmd = new Command('sync');
  cmd.description('Backward compatibility migration commands');

  cmd.command('progress')
    .description(
      'Bring progress.json up to current schema:\n' +
      '  - Coerce exec BUILDING/TESTING/COMPLETED → DRAFT (P2)\n' +
      '  - Strip legacy cso array (P17)\n' +
      '  - Add plan.pending if missing'
    )
    .action(() => {
      try {
        const projectRoot = findProjectRoot();
        runSyncProgress(projectRoot);
      } catch (e) {
        console.error((e as Error).message);
        process.exit(1);
      }
    });

  cmd.command('roadmap')
    .description(
      'Migrate existing ROADMAP file to CLI-managed format:\n' +
      '  - Extracts stage titles from FMN-PLAN files\n' +
      '  - Generates new ROADMAP with H2 headings + delimiter comments\n' +
      '  - Renames old ROADMAP to ROADMAP-vX-legacy.md\n' +
      '  - Runs sigma roadmap render to populate derived sections'
    )
    .option('--yes', 'Skip interactive APPROVE prompt')
    .action(async (opts: { yes?: boolean }) => {
      try {
        const projectRoot = findProjectRoot();
        await runSyncRoadmap(projectRoot, opts.yes ?? false);
      } catch (e) {
        console.error((e as Error).message);
        process.exit(1);
      }
    });

  return cmd;
}
