import fs from 'fs-extra';
import path from 'path';
import { PROJECT_SIGMA_DIR } from '../config';
import { ChainState, arcScoreBand, listChainVersions, readChain } from '../engine/chain';

// PLAN-EVAL-06 — Sigma/design/intent-history.md is 100% auto-render, zero manual
// sections (no SIGMA:RENDER:START/END delimiters needed, unlike renderRoadmapFile()):
// overwrite the whole file every time. Row format is a plain pipe-table on purpose —
// engine/reconstruct.ts parses it back (as a title/focus recovery source for
// `doctor --reconstruct`) with a plain pipe-split, not a markdown table parser. Keep
// the two in sync if this shape ever changes.
//
// closure-authority PLAN-EVAL-02 — two columns added (Score, Notes) for the ARC
// Satisfaction Score (Gate 3.5). Table stores only the current value per chain —
// overwritten on every `sigma intent score` re-run. Full assessment history is not
// duplicated here; it already lives in Sigma/logs/operations.jsonl by design.

export function intentHistoryPath(projectRoot: string): string {
  return path.join(projectRoot, PROJECT_SIGMA_DIR, 'design', 'intent-history.md');
}

export function generateIntentHistoryContent(chains: ChainState[]): string {
  const header = [
    '# Intent History',
    '',
    '<!-- Auto-generated by `sigma intent` (new/lock/supersede/activate/score) and `sigma doctor`. -->',
    '<!-- Do not edit by hand — Sigma CLI overwrites this file in full on every trigger. -->',
    '',
    '| Version | Title | Focus | Status | Reason | Score | Notes |',
    '| :--- | :--- | :--- | :--- | :--- | :--- | :--- |',
  ];

  const rows = chains.map(chain => {
    const { version, state, supersede_reason } = chain.intent;
    const title = chain.intent.title ?? 'TBD';
    const focus = chain.intent.focus ?? 'TBD';
    const reason = state === 'SUPERSEDED' ? (supersede_reason ?? '—') : '—';
    const score = chain.intent.arc_score !== undefined
      ? `${arcScoreBand(chain.intent.arc_score)} (${chain.intent.arc_score})`
      : '—';
    const notes = chain.intent.arc_score_notes ?? '—';
    return `| ${version} | ${title} | ${focus} | ${state} | ${reason} | ${score} | ${notes} |`;
  });

  return [...header, ...rows, ''].join('\n');
}

export function renderIntentHistoryFile(projectRoot: string): void {
  const versions = listChainVersions(projectRoot);
  if (versions.length === 0) return; // nothing to render yet — pre-`intent new`

  const chains = versions.map(v => readChain(projectRoot, v));
  const content = generateIntentHistoryContent(chains);
  const filePath = intentHistoryPath(projectRoot);
  fs.ensureDirSync(path.dirname(filePath));
  fs.writeFileSync(filePath, content, 'utf8');
}
