import fs from 'fs-extra';
import os from 'os';
import path from 'path';

interface McpServer {
  command: string;
  args: string[];
  env?: Record<string, string>;
}

interface McpJsonConfig {
  mcpServers: Record<string, McpServer>;
}

interface VscodeMcpConfig {
  servers: Record<string, McpServer>;
}

function npxCommand(packageName: string, platform: NodeJS.Platform = process.platform): { command: string; args: string[] } {
  if (platform === 'win32') {
    return { command: 'cmd', args: ['/c', 'npx', '-y', packageName] };
  }
  return { command: 'npx', args: ['-y', packageName] };
}

export function createMcpConfig(options: { platform?: NodeJS.Platform; homeDir?: string } = {}): McpJsonConfig {
  const platform = options.platform ?? process.platform;
  void options.homeDir;

  return {
    mcpServers: {
      'sequential-thinking': npxCommand('@modelcontextprotocol/server-sequential-thinking', platform),
    },
  };
}

export function createVscodeMcpConfig(options: { platform?: NodeJS.Platform; homeDir?: string } = {}): VscodeMcpConfig {
  const base = createMcpConfig(options);
  return { servers: base.mcpServers };
}

export function writeMcpJson(filePath: string, options: { platform?: NodeJS.Platform; homeDir?: string } = {}): void {
  fs.ensureDirSync(path.dirname(filePath));
  fs.writeFileSync(filePath, JSON.stringify(createMcpConfig(options), null, 2) + '\n', 'utf8');
}

export function writeVscodeMcpJson(filePath: string, options: { platform?: NodeJS.Platform; homeDir?: string } = {}): void {
  fs.ensureDirSync(path.dirname(filePath));
  fs.writeFileSync(filePath, JSON.stringify(createVscodeMcpConfig(options), null, 2) + '\n', 'utf8');
}

// Antigravity 0.43.0+ reads MCP config from ~/.gemini/antigravity/mcp_config.json.
// Server entries use the protobuf-style $typeName field required by the cascade plugin system.
// We only inject sigma-memory (always) and sequential-thinking (if not already present).
// Existing entries (e.g. Delta memory, github-mcp-server) are preserved untouched.
export function writeGeminiMcpConfig(options: { homeDir?: string } = {}): void {
  const homeDir = options.homeDir ?? os.homedir();
  const mcpConfigPath = path.join(homeDir, '.gemini', 'antigravity', 'mcp_config.json');
  const memoryFilePath = path.join(homeDir, '.sigma', 'memory_sigma.jsonl');

  const TYPENAME = 'exa.cascade_plugins_pb.CascadePluginCommandTemplate';

  let existing: Record<string, unknown> = {};
  if (fs.existsSync(mcpConfigPath)) {
    try { existing = fs.readJsonSync(mcpConfigPath); } catch { /* start fresh on parse error */ }
  }

  const existingServers = (existing.mcpServers ?? {}) as Record<string, unknown>;

  const sigmaMemoryServer = {
    $typeName: TYPENAME,
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-memory'],
    env: { MEMORY_FILE_PATH: memoryFilePath },
  };

  const sequentialThinkingServer = {
    $typeName: TYPENAME,
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-sequential-thinking'],
    env: {},
  };

  const merged: Record<string, unknown> = {
    ...existing,
    mcpServers: {
      // Preserve all existing entries (Delta memory, github-mcp-server, etc.)
      ...existingServers,
      // Only add sequential-thinking if not already configured
      ...(!existingServers['sequential-thinking'] ? { 'sequential-thinking': sequentialThinkingServer } : {}),
      // Always write sigma-memory to ensure correct MEMORY_FILE_PATH
      'sigma-memory': sigmaMemoryServer,
    },
  };

  fs.ensureDirSync(path.dirname(mcpConfigPath));
  fs.writeFileSync(mcpConfigPath, JSON.stringify(merged, null, 2) + '\n', 'utf8');
}

// Reasonix reads MCP servers exclusively from the `mcp` array in ~/.reasonix/config.json.
// That array requires the inline "name=command args" format — bare names are treated as
// built-in shorthands and are not resolved against mcpServers. mcpServers is a Claude
// Desktop / VS Code convention that Reasonix ignores for activation.
//
// To guarantee MEMORY_FILE_PATH is set (since mcpServers env is not read), sigma-memory
// is launched through a small wrapper script at ~/.sigma/mcp-run-sigma-memory.js that
// bakes the path in before spawning the MCP server process.

const SIGMA_MEMORY_WRAPPER = `#!/usr/bin/env node
// Sigma memory MCP wrapper — bakes MEMORY_FILE_PATH then spawns the server.
// Generated by sigma setup memory --reasonix. Do not edit manually.
const { spawn } = require('child_process');
const path = require('path');
const os = require('os');

const memoryFilePath = path.join(os.homedir(), '.sigma', 'memory_sigma.jsonl');
const isWin = process.platform === 'win32';
const cmd = isWin ? 'cmd' : 'npx';
const args = isWin
  ? ['/c', 'npx', '-y', '@modelcontextprotocol/server-memory']
  : ['-y', '@modelcontextprotocol/server-memory'];

const child = spawn(cmd, args, {
  stdio: 'inherit',
  env: { ...process.env, MEMORY_FILE_PATH: memoryFilePath },
});
child.on('exit', (code) => process.exit(code ?? 0));
`;

// Commands required in shellAllowed for a Sigma project to function in Reasonix.
// Reasonix uses exact-prefix matching: "sigma" alone does not cover "sigma plan new".
// Each sigma subcommand domain must be listed explicitly as a prefix.
const SIGMA_SHELL_ALLOWED = [
  // Sigma CLI — each subcommand domain as an explicit prefix
  'sigma session',
  'sigma intent',
  'sigma roadmap',
  'sigma plan',
  'sigma exec',
  'sigma close',
  'sigma project',
  'sigma setup',
  'sigma send',
  'sigma inbox',
  'sigma cso',
  'sigma git',
  'sigma override',
  'sigma config',
  'sigma refresh',
  'sigma --help',
  // Standard project tooling used by FMN/DEV roles
  'npm',
  'git',
  'ls',
];

export function writeReasonixMcpConfig(
  filePath: string,
  options: { homeDir?: string; projectRoot?: string } = {}
): { editModeChanged: boolean } {
  let existing: Record<string, unknown> = {};
  if (fs.existsSync(filePath)) {
    try { existing = fs.readJsonSync(filePath); } catch { /* ignore parse errors; start fresh */ }
  }

  const homeDir = options.homeDir ?? os.homedir();
  const sigmaDir = path.join(homeDir, '.sigma');
  const memoryFilePath = path.join(sigmaDir, 'memory_sigma.jsonl');
  const wrapperPath = path.join(sigmaDir, 'mcp-run-sigma-memory.js');

  // Deploy wrapper script so MEMORY_FILE_PATH is always set when Reasonix launches the server.
  fs.ensureDirSync(sigmaDir);
  fs.writeFileSync(wrapperPath, SIGMA_MEMORY_WRAPPER, 'utf8');

  // Reasonix mcp array inline format: "name=command arg1 arg2 ..."
  // Use forward slashes in the wrapper path — Node.js accepts them on Windows and they
  // avoid backslash escape issues inside JSON strings parsed by Reasonix.
  const wrapperPathForward = wrapperPath.replace(/\\/g, '/');
  const sigmaMcpEntries = [
    'sequential-thinking=npx -y @modelcontextprotocol/server-sequential-thinking',
    `sigma-memory=node ${wrapperPathForward}`,
    'shell=npx -y mcp-shell',
  ];

  // Strip existing entries for the names sigma manages (bare or inline format).
  const sigmaManagedNames = new Set(['sequential-thinking', 'sigma-memory', 'memory', 'shell']);
  const existingMcp: string[] = Array.isArray(existing.mcp)
    ? (existing.mcp as unknown[]).filter((e): e is string => {
        if (typeof e !== 'string') return false;
        const entryName = e.split('=')[0].trim();
        return !sigmaManagedNames.has(entryName);
      })
    : [];

  // mcpServers kept for Claude Desktop / VS Code compatibility — Reasonix also reads this.
  const sigmaServers: Record<string, McpServer> = {
    'sequential-thinking': { command: 'npx', args: ['-y', '@modelcontextprotocol/server-sequential-thinking'] },
    'sigma-memory': { command: 'npx', args: ['-y', '@modelcontextprotocol/server-memory'], env: { MEMORY_FILE_PATH: memoryFilePath } },
    'shell': { command: 'npx', args: ['-y', 'mcp-shell'] },
  };
  const existingServers = (existing.mcpServers ?? {}) as Record<string, unknown>;

  // editMode "yolo" skips all gates (file edits + shell). "auto" still gates shell commands,
  // making sigma CLI non-functional without interactive approval even with shellAllowed set.
  const previousEditMode = existing.editMode as string | undefined;
  const editModeChanged = previousEditMode !== undefined && previousEditMode !== 'yolo';
  const editMode = 'yolo';

  // Merge shellAllowed for the current project: add sigma + standard tooling if not present.
  const projectRoot = options.projectRoot ?? process.cwd();
  const existingProjects = (existing.projects ?? {}) as Record<string, Record<string, unknown>>;
  const projectEntry = existingProjects[projectRoot] ?? {};
  const existingShellAllowed = Array.isArray(projectEntry.shellAllowed)
    ? (projectEntry.shellAllowed as unknown[]).filter((c): c is string => typeof c === 'string')
    : [];
  const mergedShellAllowed = [
    ...existingShellAllowed,
    ...SIGMA_SHELL_ALLOWED.filter(cmd => !existingShellAllowed.includes(cmd)),
  ];

  const merged: Record<string, unknown> = {
    ...existing,
    editMode,
    mcp: [...existingMcp, ...sigmaMcpEntries],
    mcpServers: { ...existingServers, ...sigmaServers },
    projects: {
      ...existingProjects,
      [projectRoot]: { ...projectEntry, shellAllowed: mergedShellAllowed },
    },
  };

  fs.ensureDirSync(path.dirname(filePath));
  fs.writeFileSync(filePath, JSON.stringify(merged, null, 2) + '\n', 'utf8');

  return { editModeChanged };
}
