import fs from 'fs-extra';
import os from 'os';
import path from 'path';

interface McpServer {
  command: string;
  args: string[];
  env?: Record<string, string>;
}

interface McpJsonConfig {
  mcpServers: Record<string, McpServer>;
}

interface VscodeMcpConfig {
  servers: Record<string, McpServer>;
}


function resolveMemoryFilePath(platform: NodeJS.Platform = process.platform, homeDir = os.homedir()): string {
  const pathApi = platform === 'win32' ? path.win32 : path.posix;
  return pathApi.join(homeDir, '.sigma', 'memory_sigma.jsonl');
}

function npxCommand(packageName: string, platform: NodeJS.Platform = process.platform): { command: string; args: string[] } {
  if (platform === 'win32') {
    return { command: 'cmd', args: ['/c', 'npx', '-y', packageName] };
  }
  return { command: 'npx', args: ['-y', packageName] };
}

export function createMcpConfig(options: { platform?: NodeJS.Platform; homeDir?: string } = {}): McpJsonConfig {
  const platform = options.platform ?? process.platform;
  const homeDir = options.homeDir ?? os.homedir();

  return {
    mcpServers: {
      'sequential-thinking': npxCommand('@modelcontextprotocol/server-sequential-thinking', platform),
      'sigma-memory': {
        ...npxCommand('@modelcontextprotocol/server-memory', platform),
        env: { MEMORY_FILE_PATH: resolveMemoryFilePath(platform, homeDir) },
      },
    },
  };
}

export function createVscodeMcpConfig(options: { platform?: NodeJS.Platform; homeDir?: string } = {}): VscodeMcpConfig {
  const base = createMcpConfig(options);
  return { servers: base.mcpServers };
}

export function writeMcpJson(filePath: string, options: { platform?: NodeJS.Platform; homeDir?: string } = {}): void {
  fs.ensureDirSync(path.dirname(filePath));
  fs.writeFileSync(filePath, JSON.stringify(createMcpConfig(options), null, 2) + '\n', 'utf8');
}

export function writeVscodeMcpJson(filePath: string, options: { platform?: NodeJS.Platform; homeDir?: string } = {}): void {
  fs.ensureDirSync(path.dirname(filePath));
  fs.writeFileSync(filePath, JSON.stringify(createVscodeMcpConfig(options), null, 2) + '\n', 'utf8');
}

export function writeGeminiMcpConfig(options: { homeDir?: string } = {}): void {
  const homeDir = options.homeDir ?? os.homedir();
  const settingsPath = path.join(homeDir, '.gemini', 'settings.json');
  const memoryFilePath = path.join(homeDir, '.sigma', 'memory_sigma.jsonl');

  let existing: Record<string, unknown> = {};
  if (fs.existsSync(settingsPath)) {
    try { existing = fs.readJsonSync(settingsPath); } catch { /* ignore parse errors; start fresh */ }
  }

  const sigmaServers: Record<string, McpServer> = {
    'sequential-thinking': { command: 'npx', args: ['-y', '@modelcontextprotocol/server-sequential-thinking'] },
    'sigma-memory': { command: 'npx', args: ['-y', '@modelcontextprotocol/server-memory'], env: { MEMORY_FILE_PATH: memoryFilePath } },
  };

  const existingServers = (existing.mcpServers ?? {}) as Record<string, unknown>;
  const merged: Record<string, unknown> = {
    ...existing,
    mcpServers: { ...existingServers, ...sigmaServers },
  };

  fs.ensureDirSync(path.dirname(settingsPath));
  fs.writeFileSync(settingsPath, JSON.stringify(merged, null, 2) + '\n', 'utf8');
}

// Reasonix reads MCP servers exclusively from the `mcp` array in ~/.reasonix/config.json.
// That array requires the inline "name=command args" format — bare names are treated as
// built-in shorthands and are not resolved against mcpServers. mcpServers is a Claude
// Desktop / VS Code convention that Reasonix ignores for activation.
//
// To guarantee MEMORY_FILE_PATH is set (since mcpServers env is not read), sigma-memory
// is launched through a small wrapper script at ~/.sigma/mcp-run-sigma-memory.js that
// bakes the path in before spawning the MCP server process.

const SIGMA_MEMORY_WRAPPER = `#!/usr/bin/env node
// Sigma memory MCP wrapper — bakes MEMORY_FILE_PATH then spawns the server.
// Generated by sigma setup memory --reasonix. Do not edit manually.
const { spawn } = require('child_process');
const path = require('path');
const os = require('os');

const memoryFilePath = path.join(os.homedir(), '.sigma', 'memory_sigma.jsonl');
const isWin = process.platform === 'win32';
const cmd = isWin ? 'cmd' : 'npx';
const args = isWin
  ? ['/c', 'npx', '-y', '@modelcontextprotocol/server-memory']
  : ['-y', '@modelcontextprotocol/server-memory'];

const child = spawn(cmd, args, {
  stdio: 'inherit',
  env: { ...process.env, MEMORY_FILE_PATH: memoryFilePath },
});
child.on('exit', (code) => process.exit(code ?? 0));
`;

export function writeReasonixMcpConfig(filePath: string, options: { homeDir?: string } = {}): void {
  let existing: Record<string, unknown> = {};
  if (fs.existsSync(filePath)) {
    try { existing = fs.readJsonSync(filePath); } catch { /* ignore parse errors; start fresh */ }
  }

  const homeDir = options.homeDir ?? os.homedir();
  const sigmaDir = path.join(homeDir, '.sigma');
  const memoryFilePath = path.join(sigmaDir, 'memory_sigma.jsonl');
  const wrapperPath = path.join(sigmaDir, 'mcp-run-sigma-memory.js');

  // Deploy wrapper script so MEMORY_FILE_PATH is always set when Reasonix launches the server.
  fs.ensureDirSync(sigmaDir);
  fs.writeFileSync(wrapperPath, SIGMA_MEMORY_WRAPPER, 'utf8');

  // Reasonix mcp array inline format: "name=command arg1 arg2 ..."
  // Use forward slashes in the wrapper path — Node.js accepts them on Windows and they
  // avoid backslash escape issues inside JSON strings parsed by Reasonix.
  const wrapperPathForward = wrapperPath.replace(/\\/g, '/');
  const sigmaMcpEntries = [
    'sequential-thinking=npx -y @modelcontextprotocol/server-sequential-thinking',
    `sigma-memory=node ${wrapperPathForward}`,
  ];

  // Strip existing entries for the names sigma manages (bare or inline format).
  const sigmaManagedNames = new Set(['sequential-thinking', 'sigma-memory', 'memory']);
  const existingMcp: string[] = Array.isArray(existing.mcp)
    ? (existing.mcp as unknown[]).filter((e): e is string => {
        if (typeof e !== 'string') return false;
        const entryName = e.split('=')[0].trim();
        return !sigmaManagedNames.has(entryName);
      })
    : [];

  // mcpServers kept for Claude Desktop / VS Code compatibility — Reasonix ignores it.
  const sigmaServers: Record<string, McpServer> = {
    'sequential-thinking': { command: 'npx', args: ['-y', '@modelcontextprotocol/server-sequential-thinking'] },
    'sigma-memory': { command: 'npx', args: ['-y', '@modelcontextprotocol/server-memory'], env: { MEMORY_FILE_PATH: memoryFilePath } },
  };
  const existingServers = (existing.mcpServers ?? {}) as Record<string, unknown>;

  const merged: Record<string, unknown> = {
    ...existing,
    mcp: [...existingMcp, ...sigmaMcpEntries],
    mcpServers: { ...existingServers, ...sigmaServers },
  };

  fs.ensureDirSync(path.dirname(filePath));
  fs.writeFileSync(filePath, JSON.stringify(merged, null, 2) + '\n', 'utf8');
}
